### ISSUE TITLE
Bubble sort algorithm - infinite while loop

### ISSUE THREAD

**Issue by Phpthon** [Phpthon/virtualtourfinal#1]
![2015-02-25 18_40_30-task manager](https://cloud.githubusercontent.com/assets/5111551/6377760/787bc840-bd1e-11e4-83e5-b56fbf6483ee.png)
The bubble sort algorithm works but the while loop doesn't exit causing an infinite loop that eats the cpu.
fa75a4b3faf46b5fd7408d00f33649ca2091f883

**Comment by jordan139** [comment]
uploaded newest version of bubble sort to program ready for implementation
![image](https://cloud.githubusercontent.com/assets/9214463/6412445/c682dc8c-be7b-11e4-85db-967841d4a363.png)
